// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/dao/internal"
)

// internalHanAdminUserDao is internal type for wrapping internal DAO implements.
type internalHanAdminUserDao = *internal.HanAdminUserDao

// hanAdminUserDao is the data access object for table han_admin_user.
// You can define custom methods on it to extend its functionality as you wish.
type hanAdminUserDao struct {
	internalHanAdminUserDao
}

var (
	// HanAdminUser is globally public accessible object for table han_admin_user operations.
	HanAdminUser = hanAdminUserDao{
		internal.NewHanAdminUserDao(),
	}
)

// Fill with you ideas below.
