// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/dao/internal"
)

// internalHanAdminGroupRoleDao is internal type for wrapping internal DAO implements.
type internalHanAdminGroupRoleDao = *internal.HanAdminGroupRoleDao

// hanAdminGroupRoleDao is the data access object for table han_admin_group_role.
// You can define custom methods on it to extend its functionality as you wish.
type hanAdminGroupRoleDao struct {
	internalHanAdminGroupRoleDao
}

var (
	// HanAdminGroupRole is globally public accessible object for table han_admin_group_role operations.
	HanAdminGroupRole = hanAdminGroupRoleDao{
		internal.NewHanAdminGroupRoleDao(),
	}
)

// Fill with you ideas below.
