// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/dao/internal"
)

// internalHanAdminGroupDao is internal type for wrapping internal DAO implements.
type internalHanAdminGroupDao = *internal.HanAdminGroupDao

// hanAdminGroupDao is the data access object for table han_admin_group.
// You can define custom methods on it to extend its functionality as you wish.
type hanAdminGroupDao struct {
	internalHanAdminGroupDao
}

var (
	// HanAdminGroup is globally public accessible object for table han_admin_group operations.
	HanAdminGroup = hanAdminGroupDao{
		internal.NewHanAdminGroupDao(),
	}
)

// Fill with you ideas below.
