// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/dao/internal"
)

// internalHanAdminRoleDao is internal type for wrapping internal DAO implements.
type internalHanAdminRoleDao = *internal.HanAdminRoleDao

// hanAdminRoleDao is the data access object for table han_admin_role.
// You can define custom methods on it to extend its functionality as you wish.
type hanAdminRoleDao struct {
	internalHanAdminRoleDao
}

var (
	// HanAdminRole is globally public accessible object for table han_admin_role operations.
	HanAdminRole = hanAdminRoleDao{
		internal.NewHanAdminRoleDao(),
	}
)

// Fill with you ideas below.
