// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/dao/internal"
)

// internalHanAdminPerDao is internal type for wrapping internal DAO implements.
type internalHanAdminPerDao = *internal.HanAdminPerDao

// hanAdminPerDao is the data access object for table han_admin_per.
// You can define custom methods on it to extend its functionality as you wish.
type hanAdminPerDao struct {
	internalHanAdminPerDao
}

var (
	// HanAdminPer is globally public accessible object for table han_admin_per operations.
	HanAdminPer = hanAdminPerDao{
		internal.NewHanAdminPerDao(),
	}
)

// Fill with you ideas below.
